### ISSUE TITLE
Como trabalharemos?

### ISSUE THREAD

**Issue by pedrocecchetti** [yashin5/sciapi#5]
Tenho algumas duvidas quanto ao fluxo de trabalho que faremos. 

Com relacao a controle de versao mas tambem com relacao a outras informacoes. 

Agora o que m veio a cabeca, inicialmente é:

- Criei uma branch pra mudar a config, mas queria criar uma para adicionar o router
  - O jeito que eu fiz(puxando as duas da master faz mais sentido para voce ou fazia mais sentido puxar da banch que eu ja tinha aberto para as configs do TS?

**Comment by yashin5** [comment]
Quanto ao controle de versão podemos usar um Changelog.md, oq acha?

**Comment by yashin5** [comment]
`O jeito que eu fiz(puxando as duas da master faz mais sentido para voce ou fazia mais sentido puxar da banch que eu ja tinha aberto para as configs do TS?`


acho que faz mais sentido puxar da master, evita conflitos

**Comment by pedrocecchetti** [comment]
Entao sempre quando formos criar uma nova feat, puxamos da master, mesmo que esteja defasada. Acho que essa era uma duvida incial. Depois reabrimos a issue caso queiramos falar sobre questoes de trabalho
